# 基础镜像
FROM 192.168.1.100:3443/ci-tools/redis:latest
# author
MAINTAINER aidevops

# 挂载目录
VOLUME /home/aidevops/redis
# 创建目录
RUN mkdir -p /home/aidevops/redis
# 指定路径
WORKDIR /home/aidevops/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/aidevops/redis/redis.conf
