# 基础镜像
FROM  192.168.1.100:3443/ci-tools/eclipse-temurin:17-jre
# author
MAINTAINER aidevops

# 挂载目录
VOLUME /home/aidevops
# 创建目录
RUN mkdir -p /home/aidevops
# 指定路径
WORKDIR /home/aidevops
# 复制jar文件到路径
COPY ./jar/aidevops-visual-monitor.jar /home/aidevops/aidevops-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","aidevops-visual-monitor.jar"]