{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruoyi-ui
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.uiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ruoyi-ui
                port:
                  number: {{ .Values.ui.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruoyi-nacos
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/app-root: /nacos/
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.nacosHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ruoyi-nacos
                port:
                  number: {{ .Values.nacos.service.port }}
{{- end }}
