apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-m2-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-npm-cache-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
