server:
  port: 8080

spring:
  application:
    name: aidevops-gateway
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:application-dev.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:aidevops-gateway-dev.yml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: aidevops-nacos.aidevops-cloud.svc.cluster.local:8848
      config:
        server-addr: aidevops-nacos.aidevops-cloud.svc.cluster.local:8848
        group: DEFAULT_GROUP
        file-extension: yml
        refresh-enabled: true
    sentinel:
      eager: true
      transport:
        dashboard: aidevops-nacos.aidevops-cloud.svc.cluster.local:8718
      datasource:
        ds1:
          nacos:
            server-addr: aidevops-nacos.aidevops-cloud.svc.cluster.local:8848
            dataId: sentinel-aidevops-gateway
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
