{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aidevops-ui-root
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aidevops-ui
                port:
                  number: {{ .Values.ui.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aidevops-api
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /prod-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: aidevops-gateway
                port:
                  number: {{ .Values.gateway.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aidevops-swagger
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: aidevops-gateway
                port:
                  number: {{ .Values.gateway.servicePort }}
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: aidevops-gateway
                port:
                  number: {{ .Values.gateway.servicePort }}
          - path: /webjars
            pathType: Prefix
            backend:
              service:
                name: aidevops-gateway
                port:
                  number: {{ .Values.gateway.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aidevops-nacos
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.nacosPath }}
            pathType: Prefix
            backend:
              service:
                name: aidevops-nacos
                port:
                  number: {{ .Values.nacos.service.port }}
{{- end }}
