apiVersion: v1
kind: Service
metadata:
  name: aidevops-mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: aidevops-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: aidevops-nacos
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-nacos
  ports:
    - name: http
      port: {{ .Values.nacos.service.port }}
      targetPort: 8848
    - name: grpc1
      port: {{ .Values.nacos.service.grpc1 }}
      targetPort: 9848
    - name: grpc2
      port: {{ .Values.nacos.service.grpc2 }}
      targetPort: 9849
---
apiVersion: v1
kind: Service
metadata:
  name: aidevops-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-auth
  ports:
    - port: {{ .Values.auth.servicePort }}
      targetPort: {{ .Values.auth.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: aidevops-system
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-system
  ports:
    - port: {{ .Values.system.servicePort }}
      targetPort: {{ .Values.system.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: aidevops-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-gateway
  ports:
    - port: {{ .Values.gateway.servicePort }}
      targetPort: {{ .Values.gateway.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: aidevops-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aidevops-ui
  ports:
    - port: {{ .Values.ui.servicePort }}
      targetPort: {{ .Values.ui.servicePort }}
