images:
  initPerms: harbor.zoudekang.cloud/dockerhub-proxy/library/busybox:1.36

mysql:
  image: harbor.zoudekang.cloud/dockerhub-proxy/library/mysql:8.0
  rootPassword: password
  nfs:
    server: 192.168.1.100
    path: /data/nfs/share/aidevops-mysql

redis:
  image: harbor.zoudekang.cloud/dockerhub-proxy/library/redis:7-alpine

nacos:
  image: harbor.zoudekang.cloud/dockerhub-proxy/nacos/nacos-server:v2.2.3

auth:
  image: harbor.zoudekang.cloud/aidevops/aidevops-auth:demo

system:
  image: harbor.zoudekang.cloud/aidevops/aidevops-system:demo

gateway:
  image: harbor.zoudekang.cloud/aidevops/aidevops-gateway:demo

ui:
  image: harbor.zoudekang.cloud/aidevops/aidevops-ui:demo

ingress:
  uiHost: devops1.zoudekang.cloud
  nacosHost: nacos.zoudekang.cloud

sqlInit:
  enabled: true
  mode: bundled
