images:
  initPerms: 192.168.1.100:3443/dockerhub-proxy/library/busybox:1.36

mysql:
  image: 192.168.1.100:3443/dockerhub-proxy/library/mysql:8.0
  rootPassword: password
  nfs:
    server: 192.168.1.100
    path: /data/nfs/share/aidevops-mysql
    size: 20Gi

redis:
  image: 192.168.1.100:3443/dockerhub-proxy/library/redis:7-alpine

nacos:
  image: 192.168.1.100:3443/dockerhub-proxy/nacos/nacos-server:v2.2.3

auth:
  image: 192.168.1.100:3443/aidevops/aidevops-auth:restored-auth

system:
  image: 192.168.1.100:3443/aidevops/aidevops-system:restored-system
  aiChat:
    enabled: true
    gatewayUrl: https://ai.zoudekang.cloud/
    gatewayWsUrl: wss://ai.zoudekang.cloud/
    token: 99564a20e8fc7847ad34ed17ca86cc150b99eaa12849fa60ae894eef9a5a9e5b
    experimentalSignerEnabled: true
    probeTimeoutMs: 8000

gateway:
  image: 192.168.1.100:3443/aidevops/aidevops-gateway:release-gateway-20260330-124936

ui:
  image: 192.168.1.100:3443/aidevops/aidevops-ui:release-ui-20260330-155056

ingress:
  enabled: true
  className: nginx
  host: devops.zoudekang.cloud
  uiPath: /
  nacosPath: /nacos

sqlInit:
  enabled: true
  mode: bundled
